### ISSUE TITLE
Highlighted comment not in viewport (at least on /dialog page)

### ISSUE THREAD

**Issue by uxengine** [orbiting/republik-frontend#243]
## Bug Report

Comment deeplinks on 'Dialog' page sometimes end up at the wrong scroll position. In these cases, one typically needs to scroll further up to find the highlighted comment.

**Steps to Reproduce**

Follow a comment deeplink on the inital comments list on the dialog page, e.g.
https://www.republik.ch/dialog?t=article&id=5e45605a-eb25-4c62-8774-b1511cd9d6d0&focus=9886e76f-842d-425b-9cfb-3e81ea0808ea

**Actual Results**

Highlighted comment is above browser viewport.

**Expected Results**

Highlighted comment appears in viewport.

**Environment**
e.g. Chrome desktop and mobile

**Comment by wereHamster** [comment]
This is what happens: when the page is first rendered, all the comments are fully visible. The `focusSelector()` function focuses the comment and the viewport scrolls down. A frame or two later long comments are collapsed, which causes all the elements below to be shifted up a few pixels. 

Wrapping the call to `focusSelector()` in a short timeout (50ms) fixes this problem, as it allows the code which collapses the comments to run first, so that when `focusSelector()` runs all the positions are final.
